# Generated by Django 5.1.5 on 2025-01-30 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_userprofile_delete_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('dandruff', 'Dandruff Solutions'), ('hair_fall', 'Hair Fall Control'), ('volumizing', 'Volumizing Products'), ('nourishment', 'Nourishment Oils')], max_length=50),
        ),
    ]
