# Generated by Django 5.1.5 on 2025-02-12 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_cartitem_added_at_alter_cartitem_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('brand', 'Brand'), ('user', 'User')], default='user', max_length=10),
        ),
    ]
