# Generated by Django 5.1.5 on 2025-03-02 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_userprofile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='preferences',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
